version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - pcbridge
    expose:
      - 5432
volumes:
  db-data:
    driver: local

networks:
  pcbridge:
    driver: bridge